### ISSUE TITLE
Postage Stamp sized visualization - any way to enlarge it?

### ISSUE THREAD

**Issue by FuriouslyCurious** [zygmuntz/cubert#1]
I am getting a postage-stamp sized viewport showing rotating cube in the lower left corner of the screen.  Shouldn't the visualization take up center and most of the screen real estate?

Even turning off Dual and using Perspective mode doesn't help much.  Zooming in and out of the cube works as expected, but overall view size still remain postage stamp sized.

Attaching screenshot for reference.
<img width="1277" alt="screen shot 2016-08-09 at 1 20 25 am" src="https://cloud.githubusercontent.com/assets/8412277/17505503/836b6794-5dcf-11e6-84a2-1a4e024feefe.png">

**Comment by zygmuntz** [comment]
That is strange... I'd say, try another browser. What OS & browser are you using?
